import type { Bike } from "../backend";

// Static bike data — always available regardless of backend state
export const STATIC_BIKES: Bike[] = [
  {
    id: BigInt(1),
    name: "KTM Duke 390",
    brand: "KTM",
    category: "Naked Sports Bikes",
    price: BigInt(310000),
    photos: ["/assets/uploads/standard-obd-2b1741772118539-1--1.webp"],
    engine: "373cc",
    weight: BigInt(168),
    frame: "Steel trellis frame",
    colorOptions: ["Orange", "White"],
    description:
      "The KTM Duke 390 is a lightweight naked sports bike, perfect for street riding with aggressive styling.",
    mileage: "28 km/l",
  },
  {
    id: BigInt(2),
    name: "Triumph Speed 400",
    brand: "Triumph",
    category: "Naked Sports Bikes",
    price: BigInt(233000),
    photos: ["/assets/uploads/triumph-speed-400-standard1740985228351-13.webp"],
    engine: "398cc",
    weight: BigInt(176),
    frame: "Tubular steel frame",
    colorOptions: ["Red", "Jet Black"],
    description:
      "The Triumph Speed 400 offers a British performance motorcycle experience in a stylish naked sports package.",
    mileage: "30 km/l",
  },
  {
    id: BigInt(3),
    name: "Royal Enfield Classic 350",
    brand: "Royal Enfield",
    category: "Commuter Bikes",
    price: BigInt(195000),
    photos: ["/assets/uploads/redditch1738919737719-2.webp"],
    engine: "349cc",
    weight: BigInt(195),
    frame: "Twin downtube spine frame",
    colorOptions: ["Red", "Blue", "Chrome"],
    description:
      "The Royal Enfield Classic 350 pays tribute to the brand's legacy with vintage cruiser styling and reliable commuting.",
    mileage: "35 km/l",
  },
  {
    id: BigInt(4),
    name: "Honda CBR 650R",
    brand: "Honda",
    category: "Sports Bikes",
    price: BigInt(935000),
    photos: ["/assets/uploads/standard1747205537278-4.webp"],
    engine: "649cc",
    weight: BigInt(208),
    frame: "Diamond frame",
    colorOptions: ["Red", "Black"],
    description:
      "The Honda CBR 650R is a super-sport machine built for the track and everyday road use.",
    mileage: "25 km/l",
  },
  {
    id: BigInt(5),
    name: "TVS Apache RTR 160",
    brand: "TVS",
    category: "Commuter Bikes",
    price: BigInt(125000),
    photos: [
      "/assets/uploads/tvs-apache-160-rm-drum-black-edition1732629216165-11.webp",
    ],
    engine: "159cc",
    weight: BigInt(140),
    frame: "Double cradle frame",
    colorOptions: ["Red", "White"],
    description:
      "The TVS Apache RTR 160 is a nimble commuter with reliable performance for daily city rides.",
    mileage: "45 km/l",
  },
  {
    id: BigInt(6),
    name: "Bajaj Pulsar NS200",
    brand: "Bajaj",
    category: "Naked Sports Bikes",
    price: BigInt(150000),
    photos: [
      "/assets/uploads/bajaj-select-model-pewter-grey-1709101653302-3.webp",
    ],
    engine: "199cc",
    weight: BigInt(156),
    frame: "Perimeter frame",
    colorOptions: ["Red", "White", "Black"],
    description:
      "The Bajaj Pulsar NS200 combines awesome power with an agile naked sports bike chassis.",
    mileage: "36 km/l",
  },
  {
    id: BigInt(7),
    name: "Hero Xpulse 200",
    brand: "Hero",
    category: "Adventure Bikes",
    price: BigInt(160000),
    photos: [
      "/assets/uploads/hero-select-model-sports-red-1707139187405-12.webp",
    ],
    engine: "199cc",
    weight: BigInt(157),
    frame: "Diamond frame",
    colorOptions: ["White", "Red"],
    description:
      "The Hero Xpulse 200 is built for adventure with dual-sport capabilities and trail readiness.",
    mileage: "40 km/l",
  },
  {
    id: BigInt(8),
    name: "Suzuki Gixxer SF",
    brand: "Suzuki",
    category: "Sports Bikes",
    price: BigInt(140000),
    photos: ["/assets/uploads/ride-connect-obd-2b1742989550749-9.webp"],
    engine: "155cc",
    weight: BigInt(148),
    frame: "Diamond frame",
    colorOptions: ["Red", "Blue"],
    description:
      "The Suzuki Gixxer SF delivers sporty styling and reliable performance for everyday motorcycle enthusiasts.",
    mileage: "45 km/l",
  },
  {
    id: BigInt(9),
    name: "Kawasaki Ninja 300",
    brand: "Kawasaki",
    category: "Sports Bikes",
    price: BigInt(343000),
    photos: ["/assets/generated/kawasaki-ninja-300.dim_800x600.jpg"],
    engine: "296cc",
    weight: BigInt(179),
    frame: "Steel tube diamond frame",
    colorOptions: ["Black", "Green"],
    description:
      "The Kawasaki Ninja 300 brings iconic supersport performance to entry-level riders seeking high performance.",
    mileage: "30 km/l",
  },
  {
    id: BigInt(10),
    name: "BMW G 310 R",
    brand: "BMW",
    category: "Naked Sports Bikes",
    price: BigInt(290000),
    photos: ["/assets/generated/bmw-g310r.dim_800x600.jpg"],
    engine: "313cc",
    weight: BigInt(158),
    frame: "Tubular steel frame",
    colorOptions: ["Red", "White"],
    description:
      "The BMW G 310 R is a premium lightweight naked sports bike with athletic German engineering.",
    mileage: "32 km/l",
  },
  {
    id: BigInt(11),
    name: "Honda Hornet 2.0",
    brand: "Honda",
    category: "Naked Sports Bikes",
    price: BigInt(139000),
    photos: ["/assets/uploads/standard-obd-2b1740150415645-10.webp"],
    engine: "184cc",
    weight: BigInt(142),
    frame: "Diamond type frame",
    colorOptions: ["Red", "Blue"],
    description:
      "The Honda Hornet 2.0 packs power and agility in a lightweight frame.",
    mileage: "42 km/l",
  },
  {
    id: BigInt(12),
    name: "TVS Raider 125",
    brand: "TVS",
    category: "Commuter Bikes",
    price: BigInt(95000),
    photos: ["/assets/uploads/tvs-raider-125-drum1741766352464-7.webp"],
    engine: "124cc",
    weight: BigInt(130),
    frame: "Tubular frame",
    colorOptions: ["Red", "Blue"],
    description:
      "The TVS Raider 125 provides an awesome daily commuter experience with high fuel efficiency.",
    mileage: "60 km/l",
  },
  {
    id: BigInt(13),
    name: "Bajaj Dominar 400",
    brand: "Bajaj",
    category: "Adventure Bikes",
    price: BigInt(225000),
    photos: ["/assets/generated/bajaj-dominar-400.dim_800x600.jpg"],
    engine: "373cc",
    weight: BigInt(187),
    frame: "Perimeter frame",
    colorOptions: ["Red", "Black"],
    description:
      "The Bajaj Dominar 400 is a high-performance touring machine built for adventure and comfort.",
    mileage: "27 km/l",
  },
  {
    id: BigInt(14),
    name: "Royal Enfield Meteor 350",
    brand: "Royal Enfield",
    category: "Commuter Bikes",
    price: BigInt(205000),
    photos: [
      "/assets/uploads/royalenfield-meteor-350-fireball1757944044825-6.webp",
    ],
    engine: "349cc",
    weight: BigInt(191),
    frame: "Steel tube frame",
    colorOptions: ["Red", "Black"],
    description:
      "The Royal Enfield Meteor 350 merges classic cruiser styling with modern reliability for daily rides.",
    mileage: "35 km/l",
  },
  {
    id: BigInt(15),
    name: "KTM RC 200",
    brand: "KTM",
    category: "Sports Bikes",
    price: BigInt(218000),
    photos: [
      "/assets/uploads/ktm-select-model-gp-editiond-1670826275682-8.webp",
    ],
    engine: "199cc",
    weight: BigInt(160),
    frame: "Steel trellis frame",
    colorOptions: ["Orange", "White"],
    description:
      "The KTM RC 200 is a race-inspired sports bike engineered for high-speed performance.",
    mileage: "35 km/l",
  },
  {
    id: BigInt(16),
    name: "Suzuki Hayabusa",
    brand: "Suzuki",
    category: "Sports Bikes",
    price: BigInt(1640000),
    photos: ["/assets/uploads/standard1744377521310-5.webp"],
    engine: "1340cc",
    weight: BigInt(264),
    frame: "Twin spar frame",
    colorOptions: ["Red", "Blue"],
    description:
      "The Suzuki Hayabusa is a legendary high-speed sports motorcycle and the fastest bike on the planet.",
    mileage: "18 km/l",
  },
  {
    id: BigInt(17),
    name: "Kawasaki Z900",
    brand: "Kawasaki",
    category: "Naked Sports Bikes",
    price: BigInt(920000),
    photos: ["/assets/generated/kawasaki-z900.dim_800x600.jpg"],
    engine: "948cc",
    weight: BigInt(210),
    frame: "Trellis frame",
    colorOptions: ["Green", "Black"],
    description:
      "The Kawasaki Z900 blends high power with outstanding naked sports bike agility and control.",
    mileage: "17 km/l",
  },
  {
    id: BigInt(18),
    name: "Hero Splendor Plus",
    brand: "Hero",
    category: "Commuter Bikes",
    price: BigInt(75000),
    photos: ["/assets/uploads/drum-brake-obd-2b1744875559407-1.webp"],
    engine: "97cc",
    weight: BigInt(110),
    frame: "Cradle frame",
    colorOptions: ["Red", "Black"],
    description:
      "The Hero Splendor Plus delivers dependable and highly fuel-efficient commuting for everyday needs.",
    mileage: "70 km/l",
  },
  {
    id: BigInt(19),
    name: "Yamaha MT-15",
    brand: "Yamaha",
    category: "Naked Sports Bikes",
    price: BigInt(168000),
    photos: ["/assets/uploads/yamaha-mt-15-standard-20241759582770305-1.webp"],
    engine: "155cc",
    weight: BigInt(138),
    frame: "Delta box frame",
    colorOptions: ["Blue", "Black"],
    description:
      "The Yamaha MT-15 is an agile and lightweight naked sports bike with signature Yamaha performance.",
    mileage: "45 km/l",
  },
  {
    id: BigInt(20),
    name: "BMW S 1000 RR",
    brand: "BMW",
    category: "Sports Bikes",
    price: BigInt(2025000),
    photos: ["/assets/generated/bmw-s1000rr.dim_800x600.jpg"],
    engine: "999cc",
    weight: BigInt(197),
    frame: "Aluminum composite frame",
    colorOptions: ["Red", "Black"],
    description:
      "The BMW S 1000 RR is a superbike offering unmatched power and precision German racing engineering.",
    mileage: "15 km/l",
  },
];

export function getBikeById(id: bigint): Bike | undefined {
  return STATIC_BIKES.find((b) => b.id === id);
}
