/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import type { ActorMethod } from '@icp-sdk/core/agent';
import type { IDL } from '@icp-sdk/core/candid';
import type { Principal } from '@icp-sdk/core/principal';

export interface Bike {
  'id' : bigint,
  'weight' : [] | [bigint],
  'frame' : [] | [string],
  'colorOptions' : Array<string>,
  'mileage' : [] | [string],
  'name' : string,
  'description' : string,
  'category' : string,
  'brand' : string,
  'price' : bigint,
  'photos' : Array<string>,
  'engine' : [] | [string],
}
export interface Inquiry {
  'name' : string,
  'email' : string,
  'message' : string,
  'phone' : string,
  'bikeId' : bigint,
}
export interface _SERVICE {
  /**
   * / Adds a new bike to the catalog. Returns the new bike's unique ID.
   */
  'addBike' : ActorMethod<
    [
      string,
      string,
      string,
      bigint,
      Array<string>,
      [] | [string],
      [] | [bigint],
      [] | [string],
      Array<string>,
      string,
      [] | [string],
    ],
    undefined
  >,
  /**
   * / Returns all bikes sorted by price from lowest to highest.
   */
  'getAllBikes' : ActorMethod<[], Array<Bike>>,
  /**
   * / Returns all submitted inquiries.
   */
  'getAllInquiries' : ActorMethod<[], Array<Inquiry>>,
  /**
   * / Retrieves a single bike by its unique ID. Traps if the ID does not exist!
   */
  'getBike' : ActorMethod<[bigint], Bike>,
  /**
   * / Submits a new inquiry for a specific bike.
   */
  'submitInquiry' : ActorMethod<
    [string, string, string, bigint, string],
    undefined
  >,
}
export declare const idlService: IDL.ServiceClass;
export declare const idlInitArgs: IDL.Type[];
export declare const idlFactory: IDL.InterfaceFactory;
export declare const init: (args: { IDL: typeof IDL }) => IDL.Type[];