/* eslint-disable */

// @ts-nocheck

// This file was automatically generated by @caffeinelabs/bindgen@0.1.0.
// You should NOT make any changes in this file as it will be overwritten.
// Additionally, you should also exclude this file from your linter and/or formatter to prevent it from being checked or modified.

import { IDL } from '@icp-sdk/core/candid';

export const Bike = IDL.Record({
  'id' : IDL.Nat,
  'weight' : IDL.Opt(IDL.Nat),
  'frame' : IDL.Opt(IDL.Text),
  'colorOptions' : IDL.Vec(IDL.Text),
  'mileage' : IDL.Opt(IDL.Text),
  'name' : IDL.Text,
  'description' : IDL.Text,
  'category' : IDL.Text,
  'brand' : IDL.Text,
  'price' : IDL.Nat,
  'photos' : IDL.Vec(IDL.Text),
  'engine' : IDL.Opt(IDL.Text),
});
export const Inquiry = IDL.Record({
  'name' : IDL.Text,
  'email' : IDL.Text,
  'message' : IDL.Text,
  'phone' : IDL.Text,
  'bikeId' : IDL.Nat,
});

export const idlService = IDL.Service({
  'addBike' : IDL.Func(
      [
        IDL.Text,
        IDL.Text,
        IDL.Text,
        IDL.Nat,
        IDL.Vec(IDL.Text),
        IDL.Opt(IDL.Text),
        IDL.Opt(IDL.Nat),
        IDL.Opt(IDL.Text),
        IDL.Vec(IDL.Text),
        IDL.Text,
        IDL.Opt(IDL.Text),
      ],
      [],
      [],
    ),
  'getAllBikes' : IDL.Func([], [IDL.Vec(Bike)], ['query']),
  'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
  'getBike' : IDL.Func([IDL.Nat], [Bike], ['query']),
  'seedBikes' : IDL.Func([], [], []),
  'submitInquiry' : IDL.Func(
      [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
      [],
      [],
    ),
});

export const idlInitArgs = [];

export const idlFactory = ({ IDL }) => {
  const Bike = IDL.Record({
    'id' : IDL.Nat,
    'weight' : IDL.Opt(IDL.Nat),
    'frame' : IDL.Opt(IDL.Text),
    'colorOptions' : IDL.Vec(IDL.Text),
    'mileage' : IDL.Opt(IDL.Text),
    'name' : IDL.Text,
    'description' : IDL.Text,
    'category' : IDL.Text,
    'brand' : IDL.Text,
    'price' : IDL.Nat,
    'photos' : IDL.Vec(IDL.Text),
    'engine' : IDL.Opt(IDL.Text),
  });
  const Inquiry = IDL.Record({
    'name' : IDL.Text,
    'email' : IDL.Text,
    'message' : IDL.Text,
    'phone' : IDL.Text,
    'bikeId' : IDL.Nat,
  });
  
  return IDL.Service({
    'addBike' : IDL.Func(
        [
          IDL.Text,
          IDL.Text,
          IDL.Text,
          IDL.Nat,
          IDL.Vec(IDL.Text),
          IDL.Opt(IDL.Text),
          IDL.Opt(IDL.Nat),
          IDL.Opt(IDL.Text),
          IDL.Vec(IDL.Text),
          IDL.Text,
          IDL.Opt(IDL.Text),
        ],
        [],
        [],
      ),
    'getAllBikes' : IDL.Func([], [IDL.Vec(Bike)], ['query']),
    'getAllInquiries' : IDL.Func([], [IDL.Vec(Inquiry)], ['query']),
    'getBike' : IDL.Func([IDL.Nat], [Bike], ['query']),
    'seedBikes' : IDL.Func([], [], []),
    'submitInquiry' : IDL.Func(
        [IDL.Text, IDL.Text, IDL.Text, IDL.Nat, IDL.Text],
        [],
        [],
      ),
  });
};

export const init = ({ IDL }) => { return []; };